//! Proc-macro crate for the ARO plugin Rust SDK.
//!
//! These macros are currently pass-through stubs. Code generation is planned
//! for a future release once the macro interface is stabilised.
//!
//! # Planned macros
//!
//! | Macro | Purpose |
//! |-------|---------|
//! | `#[aro_plugin]` | Annotate a module as the plugin root; generates `aro_plugin_info` |
//! | `#[action]` | Mark a function as an action handler |
//! | `#[qualifier]` | Mark a function as a qualifier handler |
//! | `#[system_object]` | Mark a struct as a system object provider |
//! | `#[on_event]` | Mark a function as an event handler |
//! | `#[init]` | Mark a function as the plugin init hook |
//! | `#[shutdown]` | Mark a function as the plugin shutdown hook |

use proc_macro::TokenStream;

/// Annotate a module or struct as the ARO plugin root.
///
/// In a future release this will auto-generate `aro_plugin_info()`, collect
/// all `#[action]` / `#[qualifier]` handlers and wire them into the dispatch
/// table.  For now it is a no-op pass-through.
///
/// # Example
/// ```ignore
/// #[aro_plugin(name = "my-plugin", version = "1.0.0", handle = "MyPlugin")]
/// mod plugin { ... }
/// ```
#[proc_macro_attribute]
pub fn aro_plugin(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Mark a function as an ARO action handler.
///
/// In a future release the `name`, `verbs`, `role`, and `prepositions`
/// parameters will be used to generate the action metadata returned by
/// `aro_plugin_info()` and to register the function in the dispatch table
/// generated by `#[aro_plugin]`.
///
/// # Example
/// ```ignore
/// #[action(name = "my-action", verbs = ["doThing"], role = "own", prepositions = ["from"])]
/// fn handle_my_action(input: Input) -> PluginResult<Output> { ... }
/// ```
#[proc_macro_attribute]
pub fn action(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Mark a function as an ARO qualifier handler.
///
/// Qualifiers transform a single value and are invoked via the
/// `<value: Handle.qualifier>` syntax in ARO source code.
///
/// # Example
/// ```ignore
/// #[qualifier(name = "reverse")]
/// fn qualifier_reverse(input: Input) -> PluginResult<Output> { ... }
/// ```
#[proc_macro_attribute]
pub fn qualifier(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Mark a struct as an ARO system object provider.
///
/// System objects expose service-like state (e.g. database connections) that
/// ARO programs can reference as `<my-object>`.
///
/// # Example
/// ```ignore
/// #[system_object(name = "db-connection")]
/// struct DbConnection { ... }
/// ```
#[proc_macro_attribute]
pub fn system_object(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Mark a function as an ARO event handler.
///
/// # Example
/// ```ignore
/// #[on_event(event = "UserCreated")]
/// fn handle_user_created(event: EventData) -> PluginResult<Output> { ... }
/// ```
#[proc_macro_attribute]
pub fn on_event(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Mark a function as the plugin initialisation hook.
///
/// Called once when the plugin dynamic library is loaded by the ARO runtime.
///
/// # Example
/// ```ignore
/// #[init]
/// fn my_init() { /* set up global state */ }
/// ```
#[proc_macro_attribute]
pub fn init(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Mark a function as the plugin shutdown hook.
///
/// Called once when the ARO runtime unloads the plugin.
///
/// # Example
/// ```ignore
/// #[shutdown]
/// fn my_shutdown() { /* release resources */ }
/// ```
#[proc_macro_attribute]
pub fn shutdown(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}
